;==============================================================================
; 模块：系统服务与方案
; 说明：Windows 服务优化方案（默认/极速/家用/个人&网吧）、主页设置
; 文件：src\features\system\services.au3
; 函数：共 15 个
;==============================================================================
#include-once

Func DisableDesktopExp()
	_GUIDisable($Form1, 1, 45, 0x51D0F7)
	_DisableTrayMenu()
	GUISetState(@SW_SHOW, $LoadingUI)
	$aText = '正在禁用桌面体验功能..'
	RunWait(@ComSpec & ' /c dism /online /Disable-feature /featurename:DesktopExperience', @WindowsDir, @SW_HIDE)
	RunWait(@ComSpec & ' /c dism /online /Disable-feature /featurename:InkSupport', @WindowsDir, @SW_HIDE)
	GUISetState(@SW_HIDE, $LoadingUI)
	_GUIDisable($Form1, 0)
	_EnableTrayMenu()
	$aText = '正在处理，请稍后'
	MsgBox(0, '提示', '已经完成禁用桌面体验功能操作!', 5)
EndFunc   ;==>DisableDesktopExp
Func DisableNetPrinterSpt()
	_GUIDisable($Form1, 1, 45, 0x51D0F7)
	_DisableTrayMenu()
	GUISetState(@SW_SHOW, $LoadingUI)
	$aText = '正在禁用网络打印机支持..'
	RunWait(@ComSpec & ' /c dism /online /Disable-feature /featurename:Printing-InternetPrinting-Client', @WindowsDir, @SW_HIDE)
	GUISetState(@SW_HIDE, $LoadingUI)
	_GUIDisable($Form1, 0)
	_EnableTrayMenu()
	$aText = '正在处理，请稍后'
	MsgBox(0, '提示', '已经完成禁用网络打印机支持操作!', 5)
EndFunc   ;==>DisableNetPrinterSpt
Func DisableWireless()
	_GUIDisable($Form1, 1, 45, 0x51D0F7)
	_DisableTrayMenu()
	GUISetState(@SW_SHOW, $LoadingUI)
	$aText = '正在禁用无线功能..'
	RunWait(@ComSpec & ' /c dism /online /Disable-feature /featurename:WirelessNetworking', @WindowsDir, @SW_HIDE)
	GUISetState(@SW_HIDE, $LoadingUI)
	_GUIDisable($Form1, 0)
	_EnableTrayMenu()
	$aText = '正在处理，请稍后'
	MsgBox(0, '提示', '已经完成禁用无线功能!', 5)
EndFunc   ;==>DisableWireless
Func DisableTelnetCilent()
	_GUIDisable($Form1, 1, 45, 0x51D0F7)
	_DisableTrayMenu()
	GUISetState(@SW_SHOW, $LoadingUI)
	$aText = '正在禁用Telnet客户端功能..'
	RunWait(@ComSpec & ' /c dism /online /Disable-feature /featurename:TelnetClient', @WindowsDir, @SW_HIDE)
	GUISetState(@SW_HIDE, $LoadingUI)
	_GUIDisable($Form1, 0)
	_EnableTrayMenu()
	$aText = '正在处理，请稍后'
	MsgBox(0, '提示', '已经完成禁用Telnet客户端功能!', 5)
EndFunc   ;==>DisableTelnetCilent
Func DisableNetframe35()
	_GUIDisable($Form1, 1, 45, 0x51D0F7)
	_DisableTrayMenu()
	GUISetState(@SW_SHOW, $LoadingUI)
	$aText = '正在禁用NetFramework3.5..'
	RunWait(@ComSpec & ' /c dism /online /Disable-feature /featurename:TelnetClient', @WindowsDir, @SW_HIDE)
	GUISetState(@SW_HIDE, $LoadingUI)
	_GUIDisable($Form1, 0)
	_EnableTrayMenu()
	$aText = '正在处理，请稍后'
	MsgBox(0, '提示', '已经完成禁用NetFramework3.5!', 5)
EndFunc   ;==>DisableNetframe35
;win7
Func WinDefault()
	Local $SERVICE[146][3]
	$SERVICE[0][0] = 145
	$SERVICE[1][1] = "AeLookupSvc"
	$SERVICE[1][2] = "Manual"
	$SERVICE[2][1] = "ALG"
	$SERVICE[2][2] = "Manual"
	$SERVICE[3][1] = "AppIDSvc"
	$SERVICE[3][2] = "Manual"
	$SERVICE[4][1] = "Appinfo"
	$SERVICE[4][2] = "Manual"
	$SERVICE[5][1] = "AppMgmt"
	$SERVICE[5][2] = "Manual"
	$SERVICE[6][1] = "AudioEndpointBuilder"
	$SERVICE[6][2] = "Auto"
	$SERVICE[7][1] = "AudioSrv"
	$SERVICE[7][2] = "Auto"
	$SERVICE[8][1] = "AxInstSV"
	$SERVICE[8][2] = "Manual"
	$SERVICE[9][1] = "BDESVC"
	$SERVICE[9][2] = "Manual"
	$SERVICE[10][1] = "BFE"
	$SERVICE[10][2] = "Auto"
	$SERVICE[11][1] = "BITS"
	$SERVICE[11][2] = "Delayed-Auto"
	$SERVICE[12][1] = "Browser"
	$SERVICE[12][2] = "Manual"
	$SERVICE[13][1] = "bthserv"
	$SERVICE[13][2] = "Manual"
	$SERVICE[14][1] = "CertPropSvc"
	$SERVICE[14][2] = "Manual"
	$SERVICE[15][1] = "clr_optimization_v2.0.50727_32"
	$SERVICE[15][2] = "Delayed-Auto"
	$SERVICE[16][1] = "clr_optimization_v2.0.50727_64"
	$SERVICE[16][2] = "Delayed-Auto"
	$SERVICE[17][1] = "COMSysApp"
	$SERVICE[17][2] = "Manual"
	$SERVICE[18][1] = "CryptSvc"
	$SERVICE[18][2] = "Auto"
	$SERVICE[19][1] = "CscService"
	$SERVICE[19][2] = "Auto"
	$SERVICE[20][1] = "DcomLaunch"
	$SERVICE[20][2] = "Auto"
	$SERVICE[21][1] = "defragsvc"
	$SERVICE[21][2] = "Manual"
	$SERVICE[22][1] = "Dhcp"
	$SERVICE[22][2] = "Auto"
	$SERVICE[23][1] = "Dnscache"
	$SERVICE[23][2] = "Auto"
	$SERVICE[24][1] = "dot3svc"
	$SERVICE[24][2] = "Manual"
	$SERVICE[25][1] = "DPS"
	$SERVICE[25][2] = "Auto"
	$SERVICE[26][1] = "EapHost"
	$SERVICE[26][2] = "Manual"
	$SERVICE[27][1] = "EFS"
	$SERVICE[27][2] = "Manual"
	$SERVICE[28][1] = "ehRecvr"
	$SERVICE[28][2] = "Manual"
	$SERVICE[29][1] = "ehSched"
	$SERVICE[29][2] = "Manual"
	$SERVICE[30][1] = "eventlog"
	$SERVICE[30][2] = "Auto"
	$SERVICE[31][1] = "EventSystem"
	$SERVICE[31][2] = "Auto"
	$SERVICE[32][1] = "Fax"
	$SERVICE[32][2] = "Manual"
	$SERVICE[33][1] = "fdPHost"
	$SERVICE[33][2] = "Manual"
	$SERVICE[34][1] = "FDResPub"
	$SERVICE[34][2] = "Manual"
	$SERVICE[35][1] = "FontCache"
	$SERVICE[35][2] = "Delayed-Auto"
	$SERVICE[36][1] = "FontCache3.0.0.0"
	$SERVICE[36][2] = "Manual"
	$SERVICE[37][1] = "gpsvc"
	$SERVICE[37][2] = "Auto"
	$SERVICE[38][1] = "hidserv"
	$SERVICE[38][2] = "Manual"
	$SERVICE[39][1] = "hkmsvc"
	$SERVICE[39][2] = "Manual"
	$SERVICE[40][1] = "HomeGroupProvider"
	$SERVICE[40][2] = "Manual"
	$SERVICE[41][1] = "idsvc"
	$SERVICE[41][2] = "Manual"
	$SERVICE[42][1] = "IKEEXT"
	$SERVICE[42][2] = "Manual"
	$SERVICE[43][1] = "IPBusEnum"
	$SERVICE[43][2] = "Manual"
	$SERVICE[44][1] = "iphlpsvc"
	$SERVICE[44][2] = "Auto"
	$SERVICE[45][1] = "KeyIso"
	$SERVICE[45][2] = "Manual"
	$SERVICE[46][1] = "KtmRm"
	$SERVICE[46][2] = "Manual"
	$SERVICE[47][1] = "LanmanServer"
	$SERVICE[47][2] = "Auto"
	$SERVICE[48][1] = "LanmanWorkstation"
	$SERVICE[48][2] = "Auto"
	$SERVICE[49][1] = "lltdsvc"
	$SERVICE[49][2] = "Manual"
	$SERVICE[50][1] = "lmhosts"
	$SERVICE[50][2] = "Auto"
	$SERVICE[51][1] = "Mcx2Svc"
	$SERVICE[51][2] = "Disabled"
	$SERVICE[52][1] = "MMCSS"
	$SERVICE[52][2] = "Auto"
	$SERVICE[53][1] = "MpsSvc"
	$SERVICE[53][2] = "Auto"
	$SERVICE[54][1] = "MSDTC"
	$SERVICE[54][2] = "Manual"
	$SERVICE[55][1] = "MSiSCSI"
	$SERVICE[55][2] = "Manual"
	$SERVICE[56][1] = "msiserver"
	$SERVICE[56][2] = "Manual"
	$SERVICE[57][1] = "napagent"
	$SERVICE[57][2] = "Manual"
	$SERVICE[58][1] = "Netlogon"
	$SERVICE[58][2] = "Manual"
	$SERVICE[59][1] = "Netman"
	$SERVICE[59][2] = "Manual"
	$SERVICE[60][1] = "netprofm"
	$SERVICE[60][2] = "Manual"
	$SERVICE[61][1] = "NetTcpPortSharing"
	$SERVICE[61][2] = "Disabled"
	$SERVICE[62][1] = "NlaSvc"
	$SERVICE[62][2] = "Auto"
	$SERVICE[63][1] = "nsi"
	$SERVICE[63][2] = "Auto"
	$SERVICE[64][1] = "p2pimsvc"
	$SERVICE[64][2] = "Manual"
	$SERVICE[65][1] = "p2psvc"
	$SERVICE[65][2] = "Manual"
	$SERVICE[66][1] = "PcaSvc"
	$SERVICE[66][2] = "Auto"
	$SERVICE[67][1] = "PeerDistSvc"
	$SERVICE[67][2] = "Manual"
	$SERVICE[68][1] = "PerfHost"
	$SERVICE[68][2] = "Manual"
	$SERVICE[69][1] = "pla"
	$SERVICE[69][2] = "Manual"
	$SERVICE[70][1] = "PlugPlay"
	$SERVICE[70][2] = "Auto"
	$SERVICE[71][1] = "PNRPAutoReg"
	$SERVICE[71][2] = "Manual"
	$SERVICE[72][1] = "PNRPsvc"
	$SERVICE[72][2] = "Manual"
	$SERVICE[73][1] = "PolicyAgent"
	$SERVICE[73][2] = "Manual"
	$SERVICE[74][1] = "Power"
	$SERVICE[74][2] = "Auto"
	$SERVICE[75][1] = "ProfSvc"
	$SERVICE[75][2] = "Auto"
	$SERVICE[76][1] = "ProtectedStorage"
	$SERVICE[76][2] = "Manual"
	$SERVICE[77][1] = "QWAVE"
	$SERVICE[77][2] = "Manual"
	$SERVICE[78][1] = "RasAuto"
	$SERVICE[78][2] = "Manual"
	$SERVICE[79][1] = "RasMan"
	$SERVICE[79][2] = "Manual"
	$SERVICE[80][1] = "RemoteAccess"
	$SERVICE[80][2] = "Disabled"
	$SERVICE[81][1] = "RemoteRegistry"
	$SERVICE[81][2] = "Manual"
	$SERVICE[82][1] = "RpcEptMapper"
	$SERVICE[82][2] = "Auto"
	$SERVICE[83][1] = "RpcLocator"
	$SERVICE[83][2] = "Manual"
	$SERVICE[84][1] = "RpcSs"
	$SERVICE[84][2] = "Auto"
	$SERVICE[85][1] = "SamSs"
	$SERVICE[85][2] = "Auto"
	$SERVICE[86][1] = "SCardSvr"
	$SERVICE[86][2] = "Manual"
	$SERVICE[87][1] = "Schedule"
	$SERVICE[87][2] = "Auto"
	$SERVICE[88][1] = "SCPolicySvc"
	$SERVICE[88][2] = "Manual"
	$SERVICE[89][1] = "SDRSVC"
	$SERVICE[89][2] = "Manual"
	$SERVICE[90][1] = "seclogon"
	$SERVICE[90][2] = "Manual"
	$SERVICE[91][1] = "SENS"
	$SERVICE[91][2] = "Auto"
	$SERVICE[92][1] = "SensrSvc"
	$SERVICE[92][2] = "Manual"
	$SERVICE[93][1] = "SessionEnv"
	$SERVICE[93][2] = "Manual"
	$SERVICE[94][1] = "SharedAccess"
	$SERVICE[94][2] = "Disabled"
	$SERVICE[95][1] = "ShellHWDetection"
	$SERVICE[95][2] = "Auto"
	$SERVICE[96][1] = "SNMPTRAP"
	$SERVICE[96][2] = "Manual"
	$SERVICE[97][1] = "Spooler"
	$SERVICE[97][2] = "Auto"
	$SERVICE[98][1] = "sppsvc"
	$SERVICE[98][2] = "Delayed-Auto"
	$SERVICE[99][1] = "sppuinotify"
	$SERVICE[99][2] = "Manual"
	$SERVICE[100][1] = "SSDPSRV"
	$SERVICE[100][2] = "Manual"
	$SERVICE[101][1] = "SstpSvc"
	$SERVICE[101][2] = "Manual"
	$SERVICE[102][1] = "stisvc"
	$SERVICE[102][2] = "Manual"
	$SERVICE[103][1] = "swprv"
	$SERVICE[103][2] = "Manual"
	$SERVICE[104][1] = "SysMain"
	$SERVICE[104][2] = "Auto"
	$SERVICE[105][1] = "TabletInputService"
	$SERVICE[105][2] = "Manual"
	$SERVICE[106][1] = "TapiSrv"
	$SERVICE[106][2] = "Manual"
	$SERVICE[107][1] = "TBS"
	$SERVICE[107][2] = "Manual"
	$SERVICE[108][1] = "TermService"
	$SERVICE[108][2] = "Manual"
	$SERVICE[109][1] = "Themes"
	$SERVICE[109][2] = "Auto"
	$SERVICE[110][1] = "THREADORDER"
	$SERVICE[110][2] = "Manual"
	$SERVICE[111][1] = "TPAutoConnSvc"
	$SERVICE[111][2] = "Manual"
	$SERVICE[112][1] = "TPVCGateway"
	$SERVICE[112][2] = "Manual"
	$SERVICE[113][1] = "TrkWks"
	$SERVICE[113][2] = "Auto"
	$SERVICE[114][1] = "TrustedInstaller"
	$SERVICE[114][2] = "Manual"
	$SERVICE[115][1] = "UI0Detect"
	$SERVICE[115][2] = "Manual"
	$SERVICE[116][1] = "UmRdpService"
	$SERVICE[116][2] = "Manual"
	$SERVICE[117][1] = "upnphost"
	$SERVICE[117][2] = "Manual"
	$SERVICE[118][1] = "UxSms"
	$SERVICE[118][2] = "Auto"
	$SERVICE[119][1] = "VaultSvc"
	$SERVICE[119][2] = "Manual"
	$SERVICE[120][1] = "vds"
	$SERVICE[120][2] = "Manual"
	$SERVICE[121][1] = "VSS"
	$SERVICE[121][2] = "Manual"
	$SERVICE[122][1] = "W32Time"
	$SERVICE[122][2] = "Manual"
	$SERVICE[123][1] = "wbengine"
	$SERVICE[123][2] = "Manual"
	$SERVICE[124][1] = "WbioSrvc"
	$SERVICE[124][2] = "Manual"
	$SERVICE[125][1] = "wcncsvc"
	$SERVICE[125][2] = "Manual"
	$SERVICE[126][1] = "WcsPlugInService"
	$SERVICE[126][2] = "Manual"
	$SERVICE[127][1] = "WdiServiceHost"
	$SERVICE[127][2] = "Manual"
	$SERVICE[128][1] = "WdiSystemHost"
	$SERVICE[128][2] = "Manual"
	$SERVICE[129][1] = "WebClient"
	$SERVICE[129][2] = "Manual"
	$SERVICE[130][1] = "Wecsvc"
	$SERVICE[130][2] = "Manual"
	$SERVICE[131][1] = "wercplsupport"
	$SERVICE[131][2] = "Manual"
	$SERVICE[132][1] = "WerSvc"
	$SERVICE[132][2] = "Manual"
	$SERVICE[133][1] = "WinDefend"
	$SERVICE[133][2] = "Delayed-Auto"
	$SERVICE[134][1] = "WinHttpAutoProxySvc"
	$SERVICE[134][2] = "Manual"
	$SERVICE[135][1] = "Winmgmt"
	$SERVICE[135][2] = "Auto"
	$SERVICE[136][1] = "WinRM"
	$SERVICE[136][2] = "Manual"
	$SERVICE[137][1] = "wmiApSrv"
	$SERVICE[137][2] = "Manual"
	$SERVICE[138][1] = "WMPNetworkSvc"
	$SERVICE[138][2] = "Manual"
	$SERVICE[139][1] = "WPCSvc"
	$SERVICE[139][2] = "Manual"
	$SERVICE[140][1] = "WPDBusEnum"
	$SERVICE[140][2] = "Manual"
	$SERVICE[141][1] = "wscsvc"
	$SERVICE[141][2] = "Delayed-Auto"
	$SERVICE[142][1] = "WSearch"
	$SERVICE[142][2] = "Delayed-Auto"
	$SERVICE[143][1] = "wuauserv"
	$SERVICE[143][2] = "Delayed-Auto"
	$SERVICE[144][1] = "wudfsvc"
	$SERVICE[144][2] = "Manual"
	$SERVICE[145][1] = "WwanSvc"
	$SERVICE[145][2] = "Manual"
	Return $SERVICE
EndFunc   ;==>WinDefault
Func WinHighSpeed()
	Local $SERVICE[147][3]
	$SERVICE[0][0] = 146
	$SERVICE[1][1] = "AeLookupSvc"
	$SERVICE[1][2] = "Manual"
	$SERVICE[2][1] = "ALG"
	$SERVICE[2][2] = "Manual"
	$SERVICE[3][1] = "AppIDSvc"
	$SERVICE[3][2] = "Manual"
	$SERVICE[4][1] = "Appinfo"
	$SERVICE[4][2] = "Manual"
	$SERVICE[5][1] = "AppMgmt"
	$SERVICE[5][2] = "Manual"
	$SERVICE[6][1] = "AudioEndpointBuilder"
	$SERVICE[6][2] = "Auto"
	$SERVICE[7][1] = "AudioSrv"
	$SERVICE[7][2] = "Auto"
	$SERVICE[8][1] = "AxInstSV"
	$SERVICE[8][2] = "Manual"
	$SERVICE[9][1] = "BDESVC"
	$SERVICE[9][2] = "Manual"
	$SERVICE[10][1] = "BFE"
	$SERVICE[10][2] = "Auto"
	$SERVICE[11][1] = "BITS"
	$SERVICE[11][2] = "Manual"
	$SERVICE[12][1] = "Browser"
	$SERVICE[12][2] = "Disabled"
	$SERVICE[13][1] = "bthserv"
	$SERVICE[13][2] = "Manual"
	$SERVICE[14][1] = "CertPropSvc"
	$SERVICE[14][2] = "Manual"
	$SERVICE[15][1] = "clr_optimization_v2.0.50727_32"
	$SERVICE[15][2] = "Manual"
	$SERVICE[16][1] = "clr_optimization_v2.0.50727_64"
	$SERVICE[16][2] = "Manual"
	$SERVICE[17][1] = "COMSysApp"
	$SERVICE[17][2] = "Manual"
	$SERVICE[18][1] = "CryptSvc"
	$SERVICE[18][2] = "Auto"
	$SERVICE[19][1] = "CscService"
	$SERVICE[19][2] = "Auto"
	$SERVICE[20][1] = "DcomLaunch"
	$SERVICE[20][2] = "Auto"
	$SERVICE[21][1] = "defragsvc"
	$SERVICE[21][2] = "Manual"
	$SERVICE[22][1] = "Dhcp"
	$SERVICE[22][2] = "Auto"
	$SERVICE[23][1] = "Dnscache"
	$SERVICE[23][2] = "Auto"
	$SERVICE[24][1] = "dot3svc"
	$SERVICE[24][2] = "Manual"
	$SERVICE[25][1] = "DPS"
	$SERVICE[25][2] = "Auto"
	$SERVICE[26][1] = "EapHost"
	$SERVICE[26][2] = "Manual"
	$SERVICE[27][1] = "EFS"
	$SERVICE[27][2] = "Manual"
	$SERVICE[28][1] = "ehRecvr"
	$SERVICE[28][2] = "Manual"
	$SERVICE[29][1] = "ehSched"
	$SERVICE[29][2] = "Manual"
	$SERVICE[30][1] = "eventlog"
	$SERVICE[30][2] = "Auto"
	$SERVICE[31][1] = "EventSystem"
	$SERVICE[31][2] = "Auto"
	$SERVICE[32][1] = "Fax"
	$SERVICE[32][2] = "Manual"
	$SERVICE[33][1] = "fdPHost"
	$SERVICE[33][2] = "Manual"
	$SERVICE[34][1] = "FDResPub"
	$SERVICE[34][2] = "Disabled"
	$SERVICE[35][1] = "FontCache"
	$SERVICE[35][2] = "Delayed-Auto"
	$SERVICE[36][1] = "FontCache3.0.0.0"
	$SERVICE[36][2] = "Manual"
	$SERVICE[37][1] = "gpsvc"
	$SERVICE[37][2] = "Auto"
	$SERVICE[38][1] = "hidserv"
	$SERVICE[38][2] = "Manual"
	$SERVICE[39][1] = "hkmsvc"
	$SERVICE[39][2] = "Manual"
	$SERVICE[40][1] = "HomeGroupListener"
	$SERVICE[40][2] = "Manual"
	$SERVICE[41][1] = "HomeGroupProvider"
	$SERVICE[41][2] = "Manual"
	$SERVICE[42][1] = "idsvc"
	$SERVICE[42][2] = "Manual"
	$SERVICE[43][1] = "IKEEXT"
	$SERVICE[43][2] = "Manual"
	$SERVICE[44][1] = "IPBusEnum"
	$SERVICE[44][2] = "Manual"
	$SERVICE[45][1] = "iphlpsvc"
	$SERVICE[45][2] = "Disabled"
	$SERVICE[46][1] = "KeyIso"
	$SERVICE[46][2] = "Manual"
	$SERVICE[47][1] = "KtmRm"
	$SERVICE[47][2] = "Manual"
	$SERVICE[48][1] = "LanmanServer"
	$SERVICE[48][2] = "Disabled"
	$SERVICE[49][1] = "LanmanWorkstation"
	$SERVICE[49][2] = "Auto"
	$SERVICE[50][1] = "lltdsvc"
	$SERVICE[50][2] = "Manual"
	$SERVICE[51][1] = "lmhosts"
	$SERVICE[51][2] = "Disabled"
	$SERVICE[52][1] = "Mcx2Svc"
	$SERVICE[52][2] = "Disabled"
	$SERVICE[53][1] = "MMCSS"
	$SERVICE[53][2] = "Auto"
	$SERVICE[54][1] = "MpsSvc"
	$SERVICE[54][2] = "Auto"
	$SERVICE[55][1] = "MSDTC"
	$SERVICE[55][2] = "Manual"
	$SERVICE[56][1] = "MSiSCSI"
	$SERVICE[56][2] = "Manual"
	$SERVICE[57][1] = "msiserver"
	$SERVICE[57][2] = "Manual"
	$SERVICE[58][1] = "napagent"
	$SERVICE[58][2] = "Manual"
	$SERVICE[59][1] = "Netlogon"
	$SERVICE[59][2] = "Manual"
	$SERVICE[60][1] = "Netman"
	$SERVICE[60][2] = "Manual"
	$SERVICE[61][1] = "netprofm"
	$SERVICE[61][2] = "Manual"
	$SERVICE[62][1] = "NetTcpPortSharing"
	$SERVICE[62][2] = "Disabled"
	$SERVICE[63][1] = "NlaSvc"
	$SERVICE[63][2] = "Auto"
	$SERVICE[64][1] = "nsi"
	$SERVICE[64][2] = "Auto"
	$SERVICE[65][1] = "p2pimsvc"
	$SERVICE[65][2] = "Manual"
	$SERVICE[66][1] = "p2psvc"
	$SERVICE[66][2] = "Manual"
	$SERVICE[67][1] = "PcaSvc"
	$SERVICE[67][2] = "Auto"
	$SERVICE[68][1] = "PeerDistSvc"
	$SERVICE[68][2] = "Manual"
	$SERVICE[69][1] = "PerfHost"
	$SERVICE[69][2] = "Manual"
	$SERVICE[70][1] = "pla"
	$SERVICE[70][2] = "Manual"
	$SERVICE[71][1] = "PlugPlay"
	$SERVICE[71][2] = "Auto"
	$SERVICE[72][1] = "PNRPAutoReg"
	$SERVICE[72][2] = "Manual"
	$SERVICE[73][1] = "PNRPsvc"
	$SERVICE[73][2] = "Manual"
	$SERVICE[74][1] = "PolicyAgent"
	$SERVICE[74][2] = "Disabled"
	$SERVICE[75][1] = "Power"
	$SERVICE[75][2] = "Auto"
	$SERVICE[76][1] = "ProfSvc"
	$SERVICE[76][2] = "Auto"
	$SERVICE[77][1] = "ProtectedStorage"
	$SERVICE[77][2] = "Manual"
	$SERVICE[78][1] = "QWAVE"
	$SERVICE[78][2] = "Manual"
	$SERVICE[79][1] = "RasAuto"
	$SERVICE[79][2] = "Manual"
	$SERVICE[80][1] = "RasMan"
	$SERVICE[80][2] = "Manual"
	$SERVICE[81][1] = "RemoteAccess"
	$SERVICE[81][2] = "Disabled"
	$SERVICE[82][1] = "RemoteRegistry"
	$SERVICE[82][2] = "Disabled"
	$SERVICE[83][1] = "RpcEptMapper"
	$SERVICE[83][2] = "Auto"
	$SERVICE[84][1] = "RpcLocator"
	$SERVICE[84][2] = "Manual"
	$SERVICE[85][1] = "RpcSs"
	$SERVICE[85][2] = "Auto"
	$SERVICE[86][1] = "SamSs"
	$SERVICE[86][2] = "Auto"
	$SERVICE[87][1] = "SCardSvr"
	$SERVICE[87][2] = "Manual"
	$SERVICE[88][1] = "Schedule"
	$SERVICE[88][2] = "Auto"
	$SERVICE[89][1] = "SCPolicySvc"
	$SERVICE[89][2] = "Manual"
	$SERVICE[90][1] = "SDRSVC"
	$SERVICE[90][2] = "Manual"
	$SERVICE[91][1] = "seclogon"
	$SERVICE[91][2] = "Disabled"
	$SERVICE[92][1] = "SENS"
	$SERVICE[92][2] = "Disabled"
	$SERVICE[93][1] = "SensrSvc"
	$SERVICE[93][2] = "Manual"
	$SERVICE[94][1] = "SessionEnv"
	$SERVICE[94][2] = "Manual"
	$SERVICE[95][1] = "SharedAccess"
	$SERVICE[95][2] = "Disabled"
	$SERVICE[96][1] = "ShellHWDetection"
	$SERVICE[96][2] = "Auto"
	$SERVICE[97][1] = "SNMPTRAP"
	$SERVICE[97][2] = "Manual"
	$SERVICE[98][1] = "Spooler"
	$SERVICE[98][2] = "Disabled"
	$SERVICE[99][1] = "sppsvc"
	$SERVICE[99][2] = "Delayed-Auto"
	$SERVICE[100][1] = "sppuinotify"
	$SERVICE[100][2] = "Manual"
	$SERVICE[101][1] = "SSDPSRV"
	$SERVICE[101][2] = "Disabled"
	$SERVICE[102][1] = "SstpSvc"
	$SERVICE[102][2] = "Manual"
	$SERVICE[103][1] = "stisvc"
	$SERVICE[103][2] = "Disabled"
	$SERVICE[104][1] = "swprv"
	$SERVICE[104][2] = "Manual"
	$SERVICE[105][1] = "SysMain"
	$SERVICE[105][2] = "Auto"
	$SERVICE[106][1] = "TabletInputService"
	$SERVICE[106][2] = "Manual"
	$SERVICE[107][1] = "TapiSrv"
	$SERVICE[107][2] = "Manual"
	$SERVICE[108][1] = "TBS"
	$SERVICE[108][2] = "Manual"
	$SERVICE[109][1] = "TermService"
	$SERVICE[109][2] = "Manual"
	$SERVICE[110][1] = "Themes"
	$SERVICE[110][2] = "Auto"
	$SERVICE[111][1] = "THREADORDER"
	$SERVICE[111][2] = "Manual"
	$SERVICE[112][1] = "TPAutoConnSvc"
	$SERVICE[112][2] = "Manual"
	$SERVICE[113][1] = "TPVCGateway"
	$SERVICE[113][2] = "Manual"
	$SERVICE[114][1] = "TrkWks"
	$SERVICE[114][2] = "Auto"
	$SERVICE[115][1] = "TrustedInstaller"
	$SERVICE[115][2] = "Manual"
	$SERVICE[116][1] = "UI0Detect"
	$SERVICE[116][2] = "Manual"
	$SERVICE[117][1] = "UmRdpService"
	$SERVICE[117][2] = "Manual"
	$SERVICE[118][1] = "upnphost"
	$SERVICE[118][2] = "Manual"
	$SERVICE[119][1] = "UxSms"
	$SERVICE[119][2] = "Auto"
	$SERVICE[120][1] = "VaultSvc"
	$SERVICE[120][2] = "Manual"
	$SERVICE[121][1] = "vds"
	$SERVICE[121][2] = "Manual"
	$SERVICE[122][1] = "VSS"
	$SERVICE[122][2] = "Manual"
	$SERVICE[123][1] = "W32Time"
	$SERVICE[123][2] = "Auto"
	$SERVICE[124][1] = "wbengine"
	$SERVICE[124][2] = "Manual"
	$SERVICE[125][1] = "WbioSrvc"
	$SERVICE[125][2] = "Manual"
	$SERVICE[126][1] = "wcncsvc"
	$SERVICE[126][2] = "Manual"
	$SERVICE[127][1] = "WcsPlugInService"
	$SERVICE[127][2] = "Manual"
	$SERVICE[128][1] = "WdiServiceHost"
	$SERVICE[128][2] = "Manual"
	$SERVICE[129][1] = "WdiSystemHost"
	$SERVICE[129][2] = "Manual"
	$SERVICE[130][1] = "WebClient"
	$SERVICE[130][2] = "Manual"
	$SERVICE[131][1] = "Wecsvc"
	$SERVICE[131][2] = "Manual"
	$SERVICE[132][1] = "wercplsupport"
	$SERVICE[132][2] = "Manual"
	$SERVICE[133][1] = "WerSvc"
	$SERVICE[133][2] = "Disabled"
	$SERVICE[134][1] = "WinDefend"
	$SERVICE[134][2] = "Delayed-Auto"
	$SERVICE[135][1] = "WinHttpAutoProxySvc"
	$SERVICE[135][2] = "Manual"
	$SERVICE[136][1] = "Winmgmt"
	$SERVICE[136][2] = "Auto"
	$SERVICE[137][1] = "WinRM"
	$SERVICE[137][2] = "Manual"
	$SERVICE[138][1] = "wmiApSrv"
	$SERVICE[138][2] = "Manual"
	$SERVICE[139][1] = "WMPNetworkSvc"
	$SERVICE[139][2] = "Manual"
	$SERVICE[140][1] = "WPCSvc"
	$SERVICE[140][2] = "Manual"
	$SERVICE[141][1] = "WPDBusEnum"
	$SERVICE[141][2] = "Manual"
	$SERVICE[142][1] = "wscsvc"
	$SERVICE[142][2] = "Delayed-Auto"
	$SERVICE[143][1] = "WSearch"
	$SERVICE[143][2] = "Delayed-Auto"
	$SERVICE[144][1] = "wuauserv"
	$SERVICE[144][2] = "Disabled"
	$SERVICE[145][1] = "wudfsvc"
	$SERVICE[145][2] = "Manual"
	$SERVICE[146][1] = "WwanSvc"
	$SERVICE[146][2] = "Manual"
	Return $SERVICE
EndFunc   ;==>WinHighSpeed
Func WinHome()
	Local $SERVICE[148][3]
	$SERVICE[0][0] = 147
	$SERVICE[1][1] = "AeLookupSvc"
	$SERVICE[1][2] = "Manual"
	$SERVICE[2][1] = "ALG"
	$SERVICE[2][2] = "Manual"
	$SERVICE[3][1] = "AppIDSvc"
	$SERVICE[3][2] = "Manual"
	$SERVICE[4][1] = "Appinfo"
	$SERVICE[4][2] = "Manual"
	$SERVICE[5][1] = "AppMgmt"
	$SERVICE[5][2] = "Manual"
	$SERVICE[6][1] = "AudioEndpointBuilder"
	$SERVICE[6][2] = "Auto"
	$SERVICE[7][1] = "AudioSrv"
	$SERVICE[7][2] = "Auto"
	$SERVICE[8][1] = "AxInstSV"
	$SERVICE[8][2] = "Manual"
	$SERVICE[9][1] = "BDESVC"
	$SERVICE[9][2] = "Manual"
	$SERVICE[10][1] = "BFE"
	$SERVICE[10][2] = "Auto"
	$SERVICE[11][1] = "BITS"
	$SERVICE[11][2] = "Manual"
	$SERVICE[12][1] = "Browser"
	$SERVICE[12][2] = "Manual"
	$SERVICE[13][1] = "bthserv"
	$SERVICE[13][2] = "Manual"
	$SERVICE[14][1] = "CertPropSvc"
	$SERVICE[14][2] = "Manual"
	$SERVICE[15][1] = "clr_optimization_v2.0.50727_32"
	$SERVICE[15][2] = "Delayed-Auto"
	$SERVICE[16][1] = "clr_optimization_v2.0.50727_64"
	$SERVICE[16][2] = "Delayed-Auto"
	$SERVICE[17][1] = "COMSysApp"
	$SERVICE[17][2] = "Manual"
	$SERVICE[18][1] = "CryptSvc"
	$SERVICE[18][2] = "Auto"
	$SERVICE[19][1] = "CscService"
	$SERVICE[19][2] = "Auto"
	$SERVICE[20][1] = "DcomLaunch"
	$SERVICE[20][2] = "Auto"
	$SERVICE[21][1] = "defragsvc"
	$SERVICE[21][2] = "Manual"
	$SERVICE[22][1] = "Dhcp"
	$SERVICE[22][2] = "Auto"
	$SERVICE[23][1] = "Dnscache"
	$SERVICE[23][2] = "Auto"
	$SERVICE[24][1] = "dot3svc"
	$SERVICE[24][2] = "Manual"
	$SERVICE[25][1] = "DPS"
	$SERVICE[25][2] = "Auto"
	$SERVICE[26][1] = "EapHost"
	$SERVICE[26][2] = "Manual"
	$SERVICE[27][1] = "EFS"
	$SERVICE[27][2] = "Manual"
	$SERVICE[28][1] = "ehRecvr"
	$SERVICE[28][2] = "Manual"
	$SERVICE[29][1] = "ehSched"
	$SERVICE[29][2] = "Manual"
	$SERVICE[30][1] = "eventlog"
	$SERVICE[30][2] = "Auto"
	$SERVICE[31][1] = "EventSystem"
	$SERVICE[31][2] = "Auto"
	$SERVICE[32][1] = "Fax"
	$SERVICE[32][2] = "Manual"
	$SERVICE[33][1] = "fdPHost"
	$SERVICE[33][2] = "Manual"
	$SERVICE[34][1] = "FDResPub"
	$SERVICE[34][2] = "Manual"
	$SERVICE[35][1] = "FontCache"
	$SERVICE[35][2] = "Manual"
	$SERVICE[36][1] = "FontCache3.0.0.0"
	$SERVICE[36][2] = "Manual"
	$SERVICE[37][1] = "gpsvc"
	$SERVICE[37][2] = "Auto"
	$SERVICE[38][1] = "hidserv"
	$SERVICE[38][2] = "Manual"
	$SERVICE[39][1] = "hkmsvc"
	$SERVICE[39][2] = "Manual"
	$SERVICE[40][1] = "HomeGroupListener"
	$SERVICE[40][2] = "Manual"
	$SERVICE[41][1] = "HomeGroupProvider"
	$SERVICE[41][2] = "Manual"
	$SERVICE[42][1] = "idsvc"
	$SERVICE[42][2] = "Manual"
	$SERVICE[43][1] = "IKEEXT"
	$SERVICE[43][2] = "Manual"
	$SERVICE[44][1] = "IPBusEnum"
	$SERVICE[44][2] = "Manual"
	$SERVICE[45][1] = "iphlpsvc"
	$SERVICE[45][2] = "Auto"
	$SERVICE[46][1] = "KeyIso"
	$SERVICE[46][2] = "Manual"
	$SERVICE[47][1] = "KtmRm"
	$SERVICE[47][2] = "Manual"
	$SERVICE[48][1] = "LanmanServer"
	$SERVICE[48][2] = "Auto"
	$SERVICE[49][1] = "LanmanWorkstation"
	$SERVICE[49][2] = "Auto"
	$SERVICE[50][1] = "lltdsvc"
	$SERVICE[50][2] = "Manual"
	$SERVICE[51][1] = "lmhosts"
	$SERVICE[51][2] = "Auto"
	$SERVICE[52][1] = "Mcx2Svc"
	$SERVICE[52][2] = "Disabled"
	$SERVICE[53][1] = "MMCSS"
	$SERVICE[53][2] = "Auto"
	$SERVICE[54][1] = "MpsSvc"
	$SERVICE[54][2] = "Auto"
	$SERVICE[55][1] = "MSDTC"
	$SERVICE[55][2] = "Manual"
	$SERVICE[56][1] = "MSiSCSI"
	$SERVICE[56][2] = "Manual"
	$SERVICE[57][1] = "msiserver"
	$SERVICE[57][2] = "Manual"
	$SERVICE[58][1] = "napagent"
	$SERVICE[58][2] = "Manual"
	$SERVICE[59][1] = "Netlogon"
	$SERVICE[59][2] = "Manual"
	$SERVICE[60][1] = "Netman"
	$SERVICE[60][2] = "Manual"
	$SERVICE[61][1] = "netprofm"
	$SERVICE[61][2] = "Manual"
	$SERVICE[62][1] = "NetTcpPortSharing"
	$SERVICE[62][2] = "Disabled"
	$SERVICE[63][1] = "NlaSvc"
	$SERVICE[63][2] = "Auto"
	$SERVICE[64][1] = "nsi"
	$SERVICE[64][2] = "Auto"
	$SERVICE[65][1] = "p2pimsvc"
	$SERVICE[65][2] = "Manual"
	$SERVICE[66][1] = "p2psvc"
	$SERVICE[66][2] = "Manual"
	$SERVICE[67][1] = "PcaSvc"
	$SERVICE[67][2] = "Auto"
	$SERVICE[68][1] = "PeerDistSvc"
	$SERVICE[68][2] = "Manual"
	$SERVICE[69][1] = "PerfHost"
	$SERVICE[69][2] = "Manual"
	$SERVICE[70][1] = "pla"
	$SERVICE[70][2] = "Manual"
	$SERVICE[71][1] = "PlugPlay"
	$SERVICE[71][2] = "Auto"
	$SERVICE[72][1] = "PNRPAutoReg"
	$SERVICE[72][2] = "Manual"
	$SERVICE[73][1] = "PNRPsvc"
	$SERVICE[73][2] = "Manual"
	$SERVICE[74][1] = "PolicyAgent"
	$SERVICE[74][2] = "Manual"
	$SERVICE[75][1] = "Power"
	$SERVICE[75][2] = "Auto"
	$SERVICE[76][1] = "ProfSvc"
	$SERVICE[76][2] = "Auto"
	$SERVICE[77][1] = "ProtectedStorage"
	$SERVICE[77][2] = "Auto"
	$SERVICE[78][1] = "QWAVE"
	$SERVICE[78][2] = "Manual"
	$SERVICE[79][1] = "RasAuto"
	$SERVICE[79][2] = "Manual"
	$SERVICE[80][1] = "RasMan"
	$SERVICE[80][2] = "Manual"
	$SERVICE[81][1] = "RemoteAccess"
	$SERVICE[81][2] = "Disabled"
	$SERVICE[82][1] = "RemoteRegistry"
	$SERVICE[82][2] = "Manual"
	$SERVICE[83][1] = "RpcEptMapper"
	$SERVICE[83][2] = "Auto"
	$SERVICE[84][1] = "RpcLocator"
	$SERVICE[84][2] = "Manual"
	$SERVICE[85][1] = "RpcSs"
	$SERVICE[85][2] = "Auto"
	$SERVICE[86][1] = "SamSs"
	$SERVICE[86][2] = "Auto"
	$SERVICE[87][1] = "SCardSvr"
	$SERVICE[87][2] = "Manual"
	$SERVICE[88][1] = "Schedule"
	$SERVICE[88][2] = "Auto"
	$SERVICE[89][1] = "SCPolicySvc"
	$SERVICE[89][2] = "Manual"
	$SERVICE[90][1] = "SDRSVC"
	$SERVICE[90][2] = "Manual"
	$SERVICE[91][1] = "seclogon"
	$SERVICE[91][2] = "Manual"
	$SERVICE[92][1] = "SENS"
	$SERVICE[92][2] = "Auto"
	$SERVICE[93][1] = "SensrSvc"
	$SERVICE[93][2] = "Manual"
	$SERVICE[94][1] = "SessionEnv"
	$SERVICE[94][2] = "Manual"
	$SERVICE[95][1] = "SharedAccess"
	$SERVICE[95][2] = "Disabled"
	$SERVICE[96][1] = "ShellHWDetection"
	$SERVICE[96][2] = "Auto"
	$SERVICE[97][1] = "SNMPTRAP"
	$SERVICE[97][2] = "Manual"
	$SERVICE[98][1] = "Spooler"
	$SERVICE[98][2] = "Auto"
	$SERVICE[99][1] = "sppsvc"
	$SERVICE[99][2] = "Delayed-Auto"
	$SERVICE[100][1] = "sppuinotify"
	$SERVICE[100][2] = "Manual"
	$SERVICE[101][1] = "SSDPSRV"
	$SERVICE[101][2] = "Manual"
	$SERVICE[102][1] = "SstpSvc"
	$SERVICE[102][2] = "Manual"
	$SERVICE[103][1] = "stisvc"
	$SERVICE[103][2] = "Manual"
	$SERVICE[104][1] = "swprv"
	$SERVICE[104][2] = "Manual"
	$SERVICE[105][1] = "SysMain"
	$SERVICE[105][2] = "Auto"
	$SERVICE[106][1] = "TabletInputService"
	$SERVICE[106][2] = "Manual"
	$SERVICE[107][1] = "TapiSrv"
	$SERVICE[107][2] = "Manual"
	$SERVICE[108][1] = "TBS"
	$SERVICE[108][2] = "Manual"
	$SERVICE[109][1] = "TermService"
	$SERVICE[109][2] = "Manual"
	$SERVICE[110][1] = "Themes"
	$SERVICE[110][2] = "Auto"
	$SERVICE[111][1] = "THREADORDER"
	$SERVICE[111][2] = "Manual"
	$SERVICE[112][1] = "TPAutoConnSvc"
	$SERVICE[112][2] = "Manual"
	$SERVICE[113][1] = "TPVCGateway"
	$SERVICE[113][2] = "Manual"
	$SERVICE[114][1] = "TrkWks"
	$SERVICE[114][2] = "Manual"
	$SERVICE[115][1] = "TrustedInstaller"
	$SERVICE[115][2] = "Manual"
	$SERVICE[116][1] = "UI0Detect"
	$SERVICE[116][2] = "Manual"
	$SERVICE[117][1] = "UmRdpService"
	$SERVICE[117][2] = "Manual"
	$SERVICE[118][1] = "upnphost"
	$SERVICE[118][2] = "Manual"
	$SERVICE[119][1] = "UxSms"
	$SERVICE[119][2] = "Auto"
	$SERVICE[120][1] = "VaultSvc"
	$SERVICE[120][2] = "Manual"
	$SERVICE[121][1] = "vds"
	$SERVICE[121][2] = "Manual"
	$SERVICE[122][1] = "VSS"
	$SERVICE[122][2] = "Manual"
	$SERVICE[123][1] = "W32Time"
	$SERVICE[123][2] = "Auto"
	$SERVICE[124][1] = "wbengine"
	$SERVICE[124][2] = "Manual"
	$SERVICE[125][1] = "WbioSrvc"
	$SERVICE[125][2] = "Auto"
	$SERVICE[126][1] = "wcncsvc"
	$SERVICE[126][2] = "Manual"
	$SERVICE[127][1] = "WcsPlugInService"
	$SERVICE[127][2] = "Manual"
	$SERVICE[128][1] = "WdiServiceHost"
	$SERVICE[128][2] = "Manual"
	$SERVICE[129][1] = "WdiSystemHost"
	$SERVICE[129][2] = "Manual"
	$SERVICE[130][1] = "WebClient"
	$SERVICE[130][2] = "Manual"
	$SERVICE[131][1] = "Wecsvc"
	$SERVICE[131][2] = "Manual"
	$SERVICE[132][1] = "wercplsupport"
	$SERVICE[132][2] = "Manual"
	$SERVICE[133][1] = "WerSvc"
	$SERVICE[133][2] = "Manual"
	$SERVICE[134][1] = "WinDefend"
	$SERVICE[134][2] = "Delayed-Auto"
	$SERVICE[135][1] = "WinHttpAutoProxySvc"
	$SERVICE[135][2] = "Manual"
	$SERVICE[136][1] = "Winmgmt"
	$SERVICE[136][2] = "Auto"
	$SERVICE[137][1] = "WinRM"
	$SERVICE[137][2] = "Manual"
	$SERVICE[138][1] = "wmiApSrv"
	$SERVICE[138][2] = "Manual"
	$SERVICE[139][1] = "WMPNetworkSvc"
	$SERVICE[139][2] = "Manual"
	$SERVICE[140][1] = "WPCSvc"
	$SERVICE[140][2] = "Manual"
	$SERVICE[141][1] = "WPDBusEnum"
	$SERVICE[141][2] = "Manual"
	$SERVICE[142][1] = "wscsvc"
	$SERVICE[142][2] = "Delayed-Auto"
	$SERVICE[143][1] = "WSearch"
	$SERVICE[143][2] = "Delayed-Auto"
	$SERVICE[144][1] = "wuauserv"
	$SERVICE[144][2] = "Delayed-Auto"
	$SERVICE[145][1] = "wudfsvc"
	$SERVICE[145][2] = "Manual"
	$SERVICE[146][1] = "WwanSvc"
	$SERVICE[146][2] = "Manual"
	$SERVICE[147][1] = "ZhuDongFangYu"
	$SERVICE[147][2] = "Auto"
	Return $SERVICE
EndFunc   ;==>WinHome
Func WinPerson()
	Local $SERVICE[148][3]
	$SERVICE[0][0] = 147
	$SERVICE[1][1] = "AxInstSV"
	$SERVICE[2][1] = "SensrSvc"
	$SERVICE[3][1] = "AeLookupSvc"
	$SERVICE[4][1] = "AppIDSvc"
	$SERVICE[5][1] = "Appinfo"
	$SERVICE[6][1] = "ALG"
	$SERVICE[7][1] = "AppMgmt"
	$SERVICE[8][1] = "aspnet_state"
	$SERVICE[9][1] = "BITS"
	$SERVICE[10][1] = "BFE"
	$SERVICE[11][1] = "BDESVC"
	$SERVICE[12][1] = "wbengine"
	$SERVICE[13][1] = "PeerDistSvc"
	$SERVICE[14][1] = "CertPropSvc"
	$SERVICE[15][1] = "KeyIso"
	$SERVICE[16][1] = "EventSystem"
	$SERVICE[17][1] = "COMSysApp"
	$SERVICE[18][1] = "Browser"
	$SERVICE[19][1] = "VaultSvc"
	$SERVICE[20][1] = "CryptSvc"
	$SERVICE[21][1] = "DcomLaunch"
	$SERVICE[22][1] = "UxSms"
	$SERVICE[23][1] = "Dhcp"
	$SERVICE[24][1] = "DPS"
	$SERVICE[25][1] = "WdiServiceHost"
	$SERVICE[26][1] = "WdiSystemHost"
	$SERVICE[27][1] = "defragsvc"
	$SERVICE[28][1] = "TrkWks"
	$SERVICE[29][1] = "MSDTC"
	$SERVICE[30][1] = "Dnscache"
	$SERVICE[31][1] = "EFS"
	$SERVICE[32][1] = "EapHost"
	$SERVICE[33][1] = "fdPHost"
	$SERVICE[34][1] = "FDResPub"
	$SERVICE[35][1] = "gpsvc"
	$SERVICE[36][1] = "hkmsvc"
	$SERVICE[37][1] = "HomeGroupListener"
	$SERVICE[38][1] = "HomeGroupProvider"
	$SERVICE[39][1] = "hidserv"
	$SERVICE[40][1] = "IKEEXT"
	$SERVICE[41][1] = "UI0Detect"
	$SERVICE[42][1] = "SharedAccess"
	$SERVICE[43][1] = "iphlpsvc"
	$SERVICE[44][1] = "PolicyAgent"
	$SERVICE[45][1] = "KtmRm"
	$SERVICE[46][1] = "lltdsvc"
	$SERVICE[47][1] = "clr_optimization_v2.0.50727_64"
	$SERVICE[48][1] = "clr_optimization_v2.0.50727_32"
	$SERVICE[49][1] = "clr_optimization_v4.0.30319_64"
	$SERVICE[50][1] = "clr_optimization_v4.0.30319_32"
	$SERVICE[51][1] = "MSiSCSI"
	$SERVICE[52][1] = "swprv"
	$SERVICE[53][1] = "MMCSS"
	$SERVICE[54][1] = "NetMsmqActivator"
	$SERVICE[55][1] = "NetPipeActivator"
	$SERVICE[56][1] = "NetTcpActivator"
	$SERVICE[57][1] = "NetTcpPortSharing"
	$SERVICE[58][1] = "Netlogon"
	$SERVICE[59][1] = "napagent"
	$SERVICE[60][1] = "Netman"
	$SERVICE[61][1] = "netprofm"
	$SERVICE[62][1] = "NlaSvc"
	$SERVICE[63][1] = "nsi"
	$SERVICE[64][1] = "CscService"
	$SERVICE[65][1] = "WPCSvc"
	$SERVICE[66][1] = "PNRPsvc"
	$SERVICE[67][1] = "p2psvc"
	$SERVICE[68][1] = "p2pimsvc"
	$SERVICE[69][1] = "PerfHost"
	$SERVICE[70][1] = "pla"
	$SERVICE[71][1] = "PlugPlay"
	$SERVICE[72][1] = "IPBusEnum"
	$SERVICE[73][1] = "PNRPAutoReg"
	$SERVICE[74][1] = "WPDBusEnum"
	$SERVICE[75][1] = "Power"
	$SERVICE[76][1] = "Spooler"
	$SERVICE[77][1] = "wercplsupport"
	$SERVICE[78][1] = "PcaSvc"
	$SERVICE[79][1] = "ProtectedStorage"
	$SERVICE[80][1] = "QWAVE"
	$SERVICE[81][1] = "RasAuto"
	$SERVICE[82][1] = "RasMan"
	$SERVICE[83][1] = "SessionEnv"
	$SERVICE[84][1] = "TermService"
	$SERVICE[85][1] = "UmRdpService"
	$SERVICE[86][1] = "RpcSs"
	$SERVICE[87][1] = "RpcLocator"
	$SERVICE[88][1] = "RemoteRegistry"
	$SERVICE[89][1] = "RemoteAccess"
	$SERVICE[90][1] = "RpcEptMapper"
	$SERVICE[91][1] = "seclogon"
	$SERVICE[92][1] = "SstpSvc"
	$SERVICE[93][1] = "SamSs"
	$SERVICE[94][1] = "wscsvc"
	$SERVICE[95][1] = "LanmanServer"
	$SERVICE[96][1] = "ShellHWDetection"
	$SERVICE[97][1] = "SCardSvr"
	$SERVICE[98][1] = "SCPolicySvc"
	$SERVICE[99][1] = "SNMPTRAP"
	$SERVICE[100][1] = "sppsvc"
	$SERVICE[101][1] = "sppuinotify"
	$SERVICE[102][1] = "SSDPSRV"
	$SERVICE[103][1] = "StorSvc"
	$SERVICE[104][1] = "SysMain"
	$SERVICE[105][1] = "SENS"
	$SERVICE[106][1] = "TabletInputService"
	$SERVICE[107][1] = "Schedule"
	$SERVICE[108][1] = "lmhosts"
	$SERVICE[109][1] = "TapiSrv"
	$SERVICE[110][1] = "Themes"
	$SERVICE[111][1] = "THREADORDER"
	$SERVICE[112][1] = "TBS"
	$SERVICE[113][1] = "upnphost"
	$SERVICE[114][1] = "ProfSvc"
	$SERVICE[115][1] = "vds"
	$SERVICE[116][1] = "VSS"
	$SERVICE[117][1] = "WebClient"
	$SERVICE[118][1] = "AudioSrv"
	$SERVICE[119][1] = "AudioEndpointBuilder"
	$SERVICE[120][1] = "SDRSVC"
	$SERVICE[121][1] = "WbioSrvc"
	$SERVICE[122][1] = "idsvc"
	$SERVICE[123][1] = "WcsPlugInService"
	$SERVICE[124][1] = "wcncsvc"
	$SERVICE[125][1] = "wudfsvc"
	$SERVICE[126][1] = "WerSvc"
	$SERVICE[127][1] = "Wecsvc"
	$SERVICE[128][1] = "eventlog"
	$SERVICE[129][1] = "MpsSvc"
	$SERVICE[130][1] = "FontCache"
	$SERVICE[131][1] = "stisvc"
	$SERVICE[132][1] = "msiserver"
	$SERVICE[133][1] = "Winmgmt"
	$SERVICE[134][1] = "WMPNetworkSvc"
	$SERVICE[135][1] = "TrustedInstaller"
	$SERVICE[136][1] = "FontCache3.0.0.0"
	$SERVICE[137][1] = "WinRM"
	$SERVICE[138][1] = "WSearch"
	$SERVICE[139][1] = "W32Time"
	$SERVICE[140][1] = "wuauserv"
	$SERVICE[141][1] = "WinHttpAutoProxySvc"
	$SERVICE[142][1] = "dot3svc"
	$SERVICE[143][1] = "Wlansvc"
	$SERVICE[144][1] = "wmiApSrv"
	$SERVICE[145][1] = "LanmanWorkstation"
	$SERVICE[146][1] = "WwanSvc"
	$SERVICE[147][1] = "WindowsDefenderService"
	$SERVICE[1][2] = "Disable"
	$SERVICE[2][2] = "Disable"
	$SERVICE[3][2] = "Manual"
	$SERVICE[4][2] = "Manual"
	$SERVICE[5][2] = "Manual"
	$SERVICE[6][2] = "Disable"
	$SERVICE[7][2] = "Disable"
	$SERVICE[8][2] = "Disable"
	$SERVICE[9][2] = "Manual"
	$SERVICE[10][2] = "Automatic"
	$SERVICE[11][2] = "Disable"
	$SERVICE[12][2] = "Disable"
	$SERVICE[13][2] = "Disable"
	$SERVICE[14][2] = "Disable"
	$SERVICE[15][2] = "Manual"
	$SERVICE[16][2] = "Automatic"
	$SERVICE[17][2] = "Manual"
	$SERVICE[18][2] = "Manual"
	$SERVICE[19][2] = "Disable"
	$SERVICE[20][2] = "Automatic"
	$SERVICE[21][2] = "Automatic"
	$SERVICE[22][2] = "Automatic"
	$SERVICE[23][2] = "Automatic"
	$SERVICE[24][2] = "Disable"
	$SERVICE[25][2] = "Disable"
	$SERVICE[26][2] = "Disable"
	$SERVICE[27][2] = "Manual"
	$SERVICE[28][2] = "Disable"
	$SERVICE[29][2] = "Manual"
	$SERVICE[30][2] = "Automatic"
	$SERVICE[31][2] = "Disable"
	$SERVICE[32][2] = "Manual"
	$SERVICE[33][2] = "Disable"
	$SERVICE[34][2] = "Disable"
	$SERVICE[35][2] = "Automatic"
	$SERVICE[36][2] = "Disable"
	$SERVICE[37][2] = "Disable"
	$SERVICE[38][2] = "Disable"
	$SERVICE[39][2] = "Automatic"
	$SERVICE[40][2] = "Automatic"
	$SERVICE[41][2] = "Disable"
	$SERVICE[42][2] = "Disable"
	$SERVICE[43][2] = "Disable"
	$SERVICE[44][2] = "Automatic"
	$SERVICE[45][2] = "Manual"
	$SERVICE[46][2] = "Disable"
	$SERVICE[47][2] = "Manual"
	$SERVICE[48][2] = "Manual"
	$SERVICE[49][2] = "Manual"
	$SERVICE[50][2] = "Manual"
	$SERVICE[51][2] = "Automatic"
	$SERVICE[52][2] = "Manual"
	$SERVICE[53][2] = "Disable"
	$SERVICE[54][2] = "Disable"
	$SERVICE[55][2] = "Disable"
	$SERVICE[56][2] = "Disable"
	$SERVICE[57][2] = "Disable"
	$SERVICE[58][2] = "Disable"
	$SERVICE[59][2] = "Disable"
	$SERVICE[60][2] = "Manual"
	$SERVICE[61][2] = "Manual"
	$SERVICE[62][2] = "Automatic"
	$SERVICE[63][2] = "Automatic"
	$SERVICE[64][2] = "Disable"
	$SERVICE[65][2] = "Disable"
	$SERVICE[66][2] = "Disable"
	$SERVICE[67][2] = "Disable"
	$SERVICE[68][2] = "Disable"
	$SERVICE[69][2] = "Manual"
	$SERVICE[70][2] = "Manual"
	$SERVICE[71][2] = "Automatic"
	$SERVICE[72][2] = "Disable"
	$SERVICE[73][2] = "Disable"
	$SERVICE[74][2] = "Disable"
	$SERVICE[75][2] = "Automatic"
	$SERVICE[76][2] = "Disable"
	$SERVICE[77][2] = "Disable"
	$SERVICE[78][2] = "Disable"
	$SERVICE[79][2] = "Manual"
	$SERVICE[80][2] = "Disable"
	$SERVICE[81][2] = "Manual"
	$SERVICE[82][2] = "Automatic"
	$SERVICE[83][2] = "Disable"
	$SERVICE[84][2] = "Manual"
	$SERVICE[85][2] = "Disable"
	$SERVICE[86][2] = "Automatic"
	$SERVICE[87][2] = "Disable"
	$SERVICE[88][2] = "Disable"
	$SERVICE[89][2] = "Disable"
	$SERVICE[90][2] = "Automatic"
	$SERVICE[91][2] = "Manual"
	$SERVICE[92][2] = "Manual"
	$SERVICE[93][2] = "Automatic"
	$SERVICE[94][2] = "Disable"
	$SERVICE[95][2] = "Disable"
	$SERVICE[96][2] = "Automatic"
	$SERVICE[97][2] = "Disable"
	$SERVICE[98][2] = "Disable"
	$SERVICE[99][2] = "Disable"
	$SERVICE[100][2] = "Automatic"
	$SERVICE[101][2] = "Manual"
	$SERVICE[102][2] = "Manual"
	$SERVICE[103][2] = "Manual"
	$SERVICE[104][2] = "Automatic"
	$SERVICE[105][2] = "Automatic"
	$SERVICE[106][2] = "Disable"
	$SERVICE[107][2] = "Automatic"
	$SERVICE[108][2] = "Automatic"
	$SERVICE[109][2] = "Manual"
	$SERVICE[110][2] = "Automatic"
	$SERVICE[111][2] = "Manual"
	$SERVICE[112][2] = "Disable"
	$SERVICE[113][2] = "Manual"
	$SERVICE[114][2] = "Automatic"
	$SERVICE[115][2] = "Manual"
	$SERVICE[116][2] = "Manual"
	$SERVICE[117][2] = "Disable"
	$SERVICE[118][2] = "Automatic"
	$SERVICE[119][2] = "Automatic"
	$SERVICE[120][2] = "Disable"
	$SERVICE[121][2] = "Disable"
	$SERVICE[122][2] = "Manual"
	$SERVICE[123][2] = "Disable"
	$SERVICE[124][2] = "Disable"
	$SERVICE[125][2] = "Manual"
	$SERVICE[126][2] = "Disable"
	$SERVICE[127][2] = "Manual"
	$SERVICE[128][2] = "Automatic"
	$SERVICE[129][2] = "Disable"
	$SERVICE[130][2] = "Manual"
	$SERVICE[131][2] = "Manual"
	$SERVICE[132][2] = "Manual"
	$SERVICE[133][2] = "Automatic"
	$SERVICE[134][2] = "Manual"
	$SERVICE[135][2] = "Manual"
	$SERVICE[136][2] = "Manual"
	$SERVICE[137][2] = "Disable"
	$SERVICE[138][2] = "Disable"
	$SERVICE[139][2] = "Disable"
	$SERVICE[140][2] = "Manual"
	$SERVICE[141][2] = "Disable"
	$SERVICE[142][2] = "Disable"
	$SERVICE[143][2] = "Automatic"
	$SERVICE[144][2] = "Manual"
	$SERVICE[145][2] = "Manual"
	$SERVICE[146][2] = "Disable"
	$SERVICE[147][2] = "Disable"
	Return $SERVICE
EndFunc   ;==>WinPerson
Func windowsServiceTweaks()
	Local $string = GUICtrlRead($w7ServiceList)
	Local $ServiceVer, $i
	Switch $string
		Case "系统默认服务方案"
			$ServiceVer = WinDefault()
		Case "极速服务优化方案"
			$ServiceVer = WinHighSpeed()
		Case "家用服务优化方案"
			$ServiceVer = WinHome()
		Case "个人&网吧服务优化方案"
			$ServiceVer = WinPerson()
			Return 1
	EndSwitch
	For $i = 1 To UBound($ServiceVer) - 1
		Switch $ServiceVer[$i][2]
			Case "Auto"
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\ControlSet001\services\" & $ServiceVer[$i][1], "Start", "REG_DWORD", 2)
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\CurrentControlSet\Services\" & $ServiceVer[$i][1], "Start", "REG_DWORD", 2)
			Case "Delayed-Auto"
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\ControlSet001\services\" & $ServiceVer[$i][1], "Start", "REG_DWORD", 2)
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\CurrentControlSet\Services\" & $ServiceVer[$i][1], "Start", "REG_DWORD", 2)
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\ControlSet001\services\" & $ServiceVer[$i][1], "DelayedAutoStart", "REG_DWORD", 1)
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\CurrentControlSet\Services\" & $ServiceVer[$i][1], "DelayedAutoStart", "REG_DWORD", 1)
			Case "Manual"
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\ControlSet001\services\" & $ServiceVer[$i][1], "Start", "REG_DWORD", 3)
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\CurrentControlSet\Services\" & $ServiceVer[$i][1], "Start", "REG_DWORD", 3)
			Case "Disabled"
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\ControlSet001\services\" & $ServiceVer[$i][1], "Start", "REG_DWORD", 4)
				RegWrite("HKEY_LOCAL_MACHINE" & $OSFlag & "\SYSTEM\CurrentControlSet\Services\" & $ServiceVer[$i][1], "Start", "REG_DWORD", 4)
		EndSwitch
	Next
	MsgBox(0, '提示', '已经将您选择的优化项目应用到当前系统!')
EndFunc   ;==>windowsServiceTweaks
Func _SetHomePage()
	Local $HomePageUrl = GUICtrlRead($HomePage)
	If $HomePageUrl = '' Then
		$HomePageUrl = 'about:blank'
	EndIf
	RegWrite('HKEY_LOCAL_MACHINE' & $OSFlag & '\SOFTWARE\Microsoft\Internet Explorer\Main', 'Default_Page_URL', 'REG_SZ', $HomePageUrl)
	RegWrite('HKEY_LOCAL_MACHINE' & $OSFlag & '\SOFTWARE\Microsoft\Internet Explorer\Main', 'Start Page', 'REG_SZ', $HomePageUrl)
	RegWrite('HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main', 'Start Page', 'REG_SZ', $HomePageUrl)
	MsgBox(0, '提示', '设置当前计算机主页完成！！', 5)
EndFunc   ;==>_SetHomePage
Func _BackUPServiceToBat()
	Local $wbemFlagReturnImmediately = 0x10
	Local $wbemFlagForwardOnly = 0x20
	Local $colItems = ""
	Local $strComputer = "localhost"
	Local $cmdscstr = ""
	Local $objWMIService = ObjGet("winmgmts:\\" & $strComputer & "\root\CIMV2")
	$colItems = $objWMIService.ExecQuery("SELECT * FROM Win32_Service", "WQL", $wbemFlagReturnImmediately + $wbemFlagForwardOnly)
	If IsObj($colItems) Then
		Local $BatFile = FileSaveDialog('请选择您保存文件的位置', '', '批处理文件(*.bat;*.cmd)', 16)
		If @error Then Return
		For $objItem In $colItems
			$cmdscstr &= 'sc config "' & $objItem.Name & '" start= ' & _ConvertServiceStatus($objItem.StartMode) & @CRLF
		Next
		$Mainstr = '@echo off ' & @CRLF & _
				'title 计算机服务备份还原[' & @YEAR & '-' & @MON & '-' & @MDAY & ']' & @CRLF & _
				'echo 虫子樱桃提示您：正在还原系统服务状态到[' & @YEAR & '-' & @MON & '-' & @MDAY & ']' & @CRLF & _
				$cmdscstr & @CRLF & _
				'cls ' & @CRLF & _
				'echo 虫子樱桃提示您：系统服务状态已经还原到[' & @YEAR & '-' & @MON & '-' & @MDAY & ']' & @CRLF & _
				'timeout 3	'
		If Not (StringInStr($BatFile, '.bat') Or StringInStr($BatFile, '.cmd')) Then
			$BatFile &= '.bat'
		EndIf
		Local $Fh = FileOpen($BatFile, 2 + 8)
		FileWrite($Fh, $Mainstr)
		FileClose($Fh)
		MsgBox(0, '提示', '已经成功备份当前系统服务状态为批处理', 5)
	Else
		MsgBox(16, "错误", "备份系统服务状态为批处理失败！", 5)
	EndIf
EndFunc   ;==>_BackUPServiceToBat

Func _ConvertServiceStatus($sStatus)
	If $sStatus <> '' Then
		If StringUpper($sStatus) = 'MANUAL' Then
			Return 'demand'
		Else
			Return $sStatus
		EndIf
	EndIf
EndFunc   ;==>_ConvertServiceStatus
;调出IESEC界面
Func IESEC()
	Run('rundll32.exe iesetup.dll,IEShowHardeningDialog', @WindowsDir & '\system32\')
EndFunc   ;==>IESEC
